Added AF2 database search plus a few other changes
rigdenlab/MrParse pull request #11
Opened 2021-08-11 15:39 UTC by hlasimpk

There are a fair amount of changes here, but to summarise:

- Added EBI alphafold database fasta and added `mr_alphafold.py` to download and analyse the models identified by phmmr
- Updated CSS to output results from the AF2 search
- Added command line options for TMHMM and Deepcoil executables. These are needed for the classification option.
- Added config file with default arguments and executable locations, this means we only need to specify the location of the executables once.

2021-08-16 21:37 UTC, FilomenoSanchez requested changes
Nice code, I made a lot of comments but they are mostly small things so overall nice PR.

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_homolog.py
> +    return truncated_pdb_path, int(pdb_struct.molecular_weight), resolution
If `pdb_struct.molecular_weight` is a float, you should probably use `int(round(pdb_struct.molecular_weight, 0))` to convert it to a integer. I think this is more meaningful since it will not just take the first value of the float, e.g. `int(7.9)` will return 7 instead of 8.

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_pfam.py
> +             'metadata': {"description": "Model {} from region #{}".format(name, m.region_id),
This is fine but for consistency you may want to define `region_id = m.region_id` at the top and here just use `format(name, region_id)` just like you've done with the others:
```python
start = m.query_start
stop = m.query_stop
name = m.name
```

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_pfam.py
> +    return
No need for empty `return` statement

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_version.py
> +__version_info__ = (0, 2, 0)
You may want to add this to the `CHANGELOG.rst`, though I don't know if that's normally done after the PR is merged.

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_search_model.py
> +        assert self.model_hits and self.model_regions
Is it necessary to raise an `AssertionError`? You could just do:
```python
if not self.model_hits or not self.model_regions
      return None
``` 
That way you exit the function normally and don't need to have the `try/except` at lines 36-49

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_search_model.py
> +            pass
With a small modification of `def prepare_models(self)` and `def prepare_homologs(self)` you could get rid of these two `try/except`.

2021-08-16 21:37 UTC, FilomenoSanchez commented on mrparse/mr_search_model.py
>          assert self.hits and self.regions
Same as in `def prepare_models(self)`, you could do:
```python
if not self.model_hits or not self.model_regions
      return None
```
To avoid the `try/except` above.

2021-08-17 07:22 UTC, hlasimpk commented on mrparse/mr_hit.py
> +    elif dblvl == "af2":
`dblvl` gets used internally as well as externally. The `-db_lvl` argument specifies the redundancy level of the MrBUMP PDB derived sequence database for the sequence based search. The Alphafold2 search happens after this and doesn't need to be specified.

2021-08-17 08:35 UTC, hlasimpk commented on mrparse/mr_alphafold.py
> +    OBJECT_ATTRIBUTES = ['hit', 'region']
Just had a look at it appears to be supported in py3 too

2021-08-17 08:56 UTC, hlasimpk commented on mrparse/mr_search_model.py
> +        assert self.model_hits and self.model_regions
I forgot that I'd bee intending to change this! Good spot!

2021-08-17 11:05 UTC, FilomenoSanchez requested changes
Just one last thing really, after this we can just merge

2021-08-17 11:05 UTC, FilomenoSanchez commented on mrparse/mr_alphafold.py
> +    return sum(plddt_values)
Here you have the same lines of code repeated twice, it could be refactored as follows:
```python
def get_plddt(struct):
    plddt_values = []
    for chain in struct[0]:
        for residue in chain:
            plddt_values.append(residue[0].b_iso)
    return plddt_values

def calculate_avg_plddt(struct):
    plddt_values = get_plddt(struct)
    return sum(plddt_values) / len(plddt_values)

def calculate_sum_plddt(struct):
    plddt_values = get_plddt(struct)
    return sum(plddt_values) 
```

2021-08-17 11:05 UTC, FilomenoSanchez commented on mrparse/mr_alphafold.py
> +    return sum(plddt_values)
Also if you want to follow PEP-8 you should add an empty line at the end of this file

2021-08-17 11:20 UTC, FilomenoSanchez approved these changes

2021-08-17 15:04 UTC, merged