Bigafdb
rigdenlab/MrParse pull request #29
Opened 2022-09-22 09:26 UTC by rmk65

Updated with new command line options and set to version 0.3.5. New options include:
"pdb_local" - set a local PDB mirror
"use_api" -  use EBI phmmer search API (False by default)
"max_hits" - maximum number of models to prepare from each search 
"afdb_seqdb" - set path to local afdb sequence listing file (e.g. full fasta list for afdb)
"nproc" - number of CPU cores to give to Phmmer

2022-09-22 14:20 UTC, hlasimpk requested changes
Just small formatting things.

2022-09-22 14:20 UTC, hlasimpk commented on mrparse/mr_alphafold.py
> +    #pdb_name = f"AF-{hit.pdb_id}-F1-model_{database_version}.pdb"
We can remove this

2022-09-22 14:20 UTC, hlasimpk commented on mrparse/mr_hit.py
> +def find_hits(seq_info, search_engine=PHMMER, hhsearch_exe=None, hhsearch_db=None, afdb_seqdb=None, phmmer_dblvl=95, localrun=False, max_hits=10):
For consistency, can we rename localrun to local_run?

2022-09-22 14:20 UTC, hlasimpk commented on mrparse/mr_hit.py
> +        plog=open(logfile, "r")
This section could do with reformating to better fit the other code in MrParse. Basically just removing capitals from variable names, including underscores between words and adding spaces before/after = when assigning variables.

2022-09-22 14:20 UTC, hlasimpk commented on mrparse/mr_hit.py
> +def _find_json_hits(json_file, target_sequence, max_hits=10):
max hits should feed in to the json search elsewhere, in `run_phmmer_alphafold_api` there is a range `1,10` that gets parsed into the API. This returns 10 hits by default. You might want to set max hits here,

2022-09-22 14:20 UTC, hlasimpk commented on mrparse/searchDB.py
> +#! /usr/bin/env ccp4-python
I might be inclined to change the Camel case here to snake case too, although I understand it's a lot of work! There are also a few lines throughout this that are commented out, are these needed?

2022-09-22 16:26 UTC, rmk65 commented on mrparse/mr_hit.py
> +def _find_json_hits(json_file, target_sequence, max_hits=10):
Added this

2022-09-22 16:27 UTC, rmk65 commented on mrparse/mr_hit.py
> +        plog=open(logfile, "r")
Made this change.

2022-09-22 16:29 UTC, rmk65 commented on mrparse/mr_alphafold.py
> +    #pdb_name = f"AF-{hit.pdb_id}-F1-model_{database_version}.pdb"
Removed

2022-09-23 09:36 UTC, hlasimpk approved these changes

2022-09-23 09:36 UTC, merged